# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 911a5ac21ca90f4c36cafff44370bea7aef27b1ba19facfe6e54bb007f56ca2b59150310abbc357589314e3ee8e580b425b9debeaafe26f53583ca5b53a416ca

test:
  secret_key_base: 763902e3d9a8602315a23fca90cb26d63f72b9532b411439bfdb4bfc036e96626765c1225f18c0ac0cbe72693b3dac31c9ca2fb80419383bf12359d97ee2af79

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
